import React, { useEffect, useRef } from 'react';
import * as echarts from 'echarts';

export default {
  title: 'Charts/ECharts Bar Chart',
  argTypes: {
    title: { control: 'text', defaultValue: 'Aggregate Score by Location' },
    categories: { control: 'object', defaultValue: ['Location A', 'Location B', 'Location C', 'Location D', 'Location E', 'Location F', 'Location G'] },
    darkMode: { control: 'text', defaultValue: 'auto' },
    colorBy: { control: 'text', defaultValue: 'series' },
    color: { control: 'object', defaultValue: [
      '#5540e1',
      '#ce7afd',
      '#82ecff',
      '#ffbf51',
      '#14868f',
      '#cc224b',
      '#121224',
      '#ece3fd'
    ] },
    gradientColor: { control: 'object', defaultValue: ['#f6efa6', '#d88273', '#bf444c'] },
    aria: { control: 'object', defaultValue: {} },
    textStyle: { control: 'object', defaultValue: { fontFamily: 'sans-serif', fontSize: 12, fontStyle: 'normal', fontWeight: 'normal' } },
    animation: { control: 'text', defaultValue: 'auto' },
    animationDuration: { control: 'number', defaultValue: 1000 },
    animationDurationUpdate: { control: 'number', defaultValue: 500 },
    animationEasing: { control: 'text', defaultValue: 'cubicInOut' },
    animationEasingUpdate: { control: 'text', defaultValue: 'cubicInOut' },
    animationThreshold: { control: 'number', defaultValue: 2000 },
    progressiveThreshold: { control: 'number', defaultValue: 3000 },
    progressive: { control: 'number', defaultValue: 400 },
    hoverLayerThreshold: { control: 'number', defaultValue: 3000 },
    useUTC: { control: 'boolean', defaultValue: false },
    axisPointer: { control: 'object', defaultValue: {} },
    yAxis: { control: 'object', defaultValue: [{
      show: true,
      type: 'value',
      name: 'Aggregate Score',
      nameLocation: 'middle',
      nameTextStyle: { fontWeight: 'bold', fontSize: 14 },
      nameGap: 40,
      nameRotate: 90,
      axisLine: { show: true, lineStyle: { color: '#333' } },
      axisTick: { show: true },
      axisLabel: { show: true, fontSize: 12 },
      splitLine: { show: true, lineStyle: { type: 'dashed' } },
      splitArea: { show: false },
      min: null,
      max: null,
      interval: null,
      boundaryGap: [0, 0],
      inverse: false,
      position: 'left',
      offset: 0,
      alignTicks: false,
      scale: false,
      z: 0,
      zlevel: 0,
      gridIndex: 0
    }] },
    xAxis: { control: 'object', defaultValue: [{
      show: true,
      type: 'category',
      name: 'Location',
      nameLocation: 'middle',
      nameTextStyle: { fontWeight: 'bold', fontSize: 14 },
      nameGap: 30,
      nameRotate: 0,
      axisLine: { show: true, lineStyle: { color: '#333' } },
      axisTick: { show: true },
      axisLabel: { show: true, fontSize: 12 },
      splitLine: { show: false },
      splitArea: { show: false },
      min: null,
      max: null,
      interval: 1,
      boundaryGap: true,
      inverse: false,
      position: 'bottom',
      offset: 0,
      alignTicks: false,
      scale: false,
      z: 0,
      zlevel: 0,
      gridIndex: 0,
      }] },
    grid: { control: 'object', defaultValue: [{ show: false, z: 0, left: '10%', top: 60, right: '10%', bottom: 70, containLabel: false, backgroundColor: 'rgba(0,0,0,0)', borderWidth: 1, borderColor: '#ccc' }] },
    series: { control: 'object', defaultValue: [
      {
        name: 'Aggregate Score',
        data: [80, 90, 70, 60, 85, 95, 75],
        type: 'bar',
        z: 2,
        coordinateSystem: 'cartesian2d',
        legendHoverLink: true,
        barMinHeight: 0,
        barMinAngle: 0,
        large: false,
        largeThreshold: 400,
        progressive: 3000,
        progressiveChunkMode: 'mod',
        clip: true,
        roundCap: false,
        showBackground: false,
        backgroundStyle: { color: 'rgba(180, 180, 180, 0.2)' },
        opacity: 1,
        select: { itemStyle: { borderColor: '#212121' } },
        realtimeSort: false
      },
      {
        name: 'Score (30 Days)',
        data: [60, 75, 65, 55, 80, 85, 70],
        type: 'bar',
        z: 2,
        coordinateSystem: 'cartesian2d',
        legendHoverLink: true,
        barMinHeight: 0,
        barMinAngle: 0,
        large: false,
        largeThreshold: 400,
        progressive: 3000,
        progressiveChunkMode: 'mod',
        clip: true,
        roundCap: false,
        showBackground: false,
        backgroundStyle: { color: 'rgba(180, 180, 180, 0.2)' },
        opacity: 1,
        select: { itemStyle: { borderColor: '#212121' } },
        realtimeSort: false
      }
    ] },
    width: { control: 'number', defaultValue: 800 },
    height: { control: 'number', defaultValue: 500 },
  },
};

const EChartsBarChart = ({ title, categories, width = 800, height = 500, ...rest }) => {
  const chartRef = useRef(null);

  useEffect(() => {
    const option = {
      title: { text: title },
      xAxis: rest.xAxis || [{
        show: true,
        type: 'category',
        name: 'Location',
        nameLocation: 'middle',
        nameTextStyle: { fontWeight: 'bold', fontSize: 14 },
        nameGap: 30,
        nameRotate: 0,
        axisLine: { show: true, lineStyle: { color: '#333' } },
        axisTick: { show: true },
        axisLabel: { show: true, fontSize: 12 },
        splitLine: { show: false },
        splitArea: { show: false },
        min: null,
        max: null,
        interval: 1,
        boundaryGap: true,
        inverse: false,
        position: 'bottom',
        offset: 0,
        alignTicks: false,
        scale: false,
        z: 0,
        zlevel: 0,
        gridIndex: 0,
        data: categories
      }],
      yAxis: rest.yAxis || [{
        show: true,
        type: 'value',
        name: 'Aggregate Score',
        nameLocation: 'middle',
        nameTextStyle: { fontWeight: 'bold', fontSize: 14 },
        nameGap: 40,
        nameRotate: 90,
        axisLine: { show: true, lineStyle: { color: '#333' } },
        axisTick: { show: true },
        axisLabel: { show: true, fontSize: 12 },
        splitLine: { show: true, lineStyle: { type: 'dashed' } },
        splitArea: { show: false },
        min: null,
        max: null,
        interval: null,
        boundaryGap: [0, 0],
        inverse: false,
        position: 'left',
        offset: 0,
        alignTicks: false,
        scale: false,
        z: 0,
        zlevel: 0,
        gridIndex: 0
      }],
      series: rest.series,
      darkMode: rest.darkMode,
      colorBy: rest.colorBy,
      color: rest.color,
      gradientColor: rest.gradientColor,
      aria: rest.aria,
      textStyle: rest.textStyle,
      animation: rest.animation,
      animationDuration: rest.animationDuration,
      animationDurationUpdate: rest.animationDurationUpdate,
      animationEasing: rest.animationEasing,
      animationEasingUpdate: rest.animationEasingUpdate,
      animationThreshold: rest.animationThreshold,
      progressiveThreshold: rest.progressiveThreshold,
      progressive: rest.progressive,
      hoverLayerThreshold: rest.hoverLayerThreshold,
      useUTC: rest.useUTC,
      axisPointer: rest.axisPointer,
      grid: rest.grid,
    };
    const chart = echarts.init(chartRef.current);
    chart.setOption(option);
    return () => chart.dispose();
  }, [title, categories, rest]);

  return <div ref={chartRef} style={{ width, height }} />;
};

export const Basic = EChartsBarChart.bind({});
Basic.args = {
  title: 'Aggregate Score by Location',
  categories: ['Location A', 'Location B', 'Location C', 'Location D', 'Location E', 'Location F', 'Location G'],
  darkMode: 'auto',
  colorBy: 'series',
  color: [
    '#5540e1',
    '#ce7afd',
    '#82ecff',
    '#ffbf51',
    '#14868f',
    '#cc224b',
    '#121224',
    '#ece3fd'
  ],
  gradientColor: ['#f6efa6', '#d88273', '#bf444c'],
  aria: {},
  textStyle: { fontFamily: 'sans-serif', fontSize: 12, fontStyle: 'normal', fontWeight: 'normal' },
  animation: 'auto',
  animationDuration: 1000,
  animationDurationUpdate: 500,
  animationEasing: 'cubicInOut',
  animationEasingUpdate: 'cubicInOut',
  animationThreshold: 2000,
  progressiveThreshold: 3000,
  progressive: 400,
  hoverLayerThreshold: 3000,
  useUTC: false,
  axisPointer: {},
  yAxis: [{
    show: true,
    type: 'value',
    name: 'Aggregate Score',
    nameLocation: 'middle',
    nameTextStyle: { fontWeight: 'bold', fontSize: 14 },
    nameGap: 40,
    nameRotate: 90,
    axisLine: { show: true, lineStyle: { color: '#333' } },
    axisTick: { show: true },
    axisLabel: { show: true, fontSize: 12 },
    splitLine: { show: true, lineStyle: { type: 'dashed' } },
    splitArea: { show: false },
    min: null,
    max: null,
    interval: null,
    boundaryGap: [0, 0],
    inverse: false,
    position: 'left',
    offset: 0,
    alignTicks: false,
    scale: false,
    z: 0,
    zlevel: 0,
    gridIndex: 0
  }],
  xAxis: [{
    show: true,
    type: 'category',
    name: 'Location',
    nameLocation: 'middle',
    nameTextStyle: { fontWeight: 'bold', fontSize: 14 },
    nameGap: 30,
    nameRotate: 0,
    axisLine: { show: true, lineStyle: { color: '#333' } },
    axisTick: { show: true },
    axisLabel: { show: true, fontSize: 12 },
    splitLine: { show: false },
    splitArea: { show: false },
    min: null,
    max: null,
    interval: 1,
    boundaryGap: true,
    inverse: false,
    position: 'bottom',
    offset: 0,
    alignTicks: false,
    scale: false,
    z: 0,
    zlevel: 0,
    gridIndex: 0,
  }],
  grid: [{ show: false, z: 0, left: '10%', top: 60, right: '10%', bottom: 70, containLabel: false, backgroundColor: 'rgba(0,0,0,0)', borderWidth: 1, borderColor: '#ccc' }],
  series: [
    {
      name: 'Aggregate Score',
      data: [80, 90, 70, 60, 85, 95, 75],
      type: 'bar',
      z: 2,
      coordinateSystem: 'cartesian2d',
      legendHoverLink: true,
      barMinHeight: 0,
      barMinAngle: 0,
      large: false,
      largeThreshold: 400,
      progressive: 3000,
      progressiveChunkMode: 'mod',
      clip: true,
      roundCap: false,
      showBackground: false,
      backgroundStyle: { color: 'rgba(180, 180, 180, 0.2)' },
      opacity: 1,
      select: { itemStyle: { borderColor: '#212121' } },
      realtimeSort: false
    },
    {
      name: 'Score (30 Days)',
      data: [60, 75, 65, 55, 80, 85, 70],
      type: 'bar',
      z: 2,
      coordinateSystem: 'cartesian2d',
      legendHoverLink: true,
      barMinHeight: 0,
      barMinAngle: 0,
      large: false,
      largeThreshold: 400,
      progressive: 3000,
      progressiveChunkMode: 'mod',
      clip: true,
      roundCap: false,
      showBackground: false,
      backgroundStyle: { color: 'rgba(180, 180, 180, 0.2)' },
      opacity: 1,
      select: { itemStyle: { borderColor: '#212121' } },
      realtimeSort: false
    }
  ],
  width: 800,
  height: 500,
}; 